# =========================
# HTTP (PORT 80)
# =========================
server {
    listen 80;
    server_name dev-e-transac.abrisud.fr;

    location /.well-known/acme-challenge/ {
        alias /var/www/certbot/.well-known/acme-challenge/;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# =========================
# HTTPS (PORT 443)
# =========================
server {
    listen 443 ssl;
    server_name dev-e-transac.abrisud.fr;

    ssl_certificate /etc/letsencrypt/live/dev-e-transac.abrisud.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dev-e-transac.abrisud.fr/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    add_header Strict-Transport-Security "max-age=31536000" always;

    location /imgbridge/ {
        proxy_pass http://imgbridge-app:80/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /pinpo/ {
        proxy_pass http://pinpo-app:80/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /linxo/api/ {
        proxy_pass http://linxo-api:80/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /linxo/webhook/ {
        proxy_pass http://linxo-webhook:80/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}